version: '3.8'
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge
